import { z } from "zod";

export const Skill = z.enum([
  "0ne Sh0t 0ne Kill",
  "0ptics",
  "20% Cooler",
  "5 Shots or 6",
  "Able",
  "Accelerate",
  "Aerial Impact",
  "Aid Station",
  "All I Need is One",
  "All in the Reflexes",
  "Ambush",
  "Annoyed Android",
  "Asbestos",
  "Assault",
  "Backdraft",
  "Backstab",
  "Barrage",
  "Bash",
  "Battlefront",
  "Be Like Water",
  "Bird of Prey",
  "Blackout",
  "Blight Phoenix",
  "Blood Bath",
  "Blood Overdrive",
  "Blood Sport",
  "Blood Trance",
  "Blood Twitch",
  "Blood-Filled Guns",
  "Boiling Blood",
  "Burn, Baby, Burn",
  "C0unter Strike",
  "Caliber",
  "Carrion Call",
  "Cast Iron",
  "Cauterize",
  "Chain Reaction",
  "Cooking Up Trouble",
  "Deadly",
  "Death From Above",
  "Defense",
  "Deploy",
  "Diehard",
  "Diva",
  "Divergent Likeness",
  "Dramatic Entrance",
  "Duty Calls",
  "Elated",
  "Electrical Burn",
  "Elemental Elation",
  "Embrace the Pain",
  "Empty the Rage",
  "Endless Rage",
  "Endowed",
  "Enforcer",
  "Evil Enchantress",
  "Expertise",
  "F0ll0wthr0ugh",
  "Fancy Mathematics",
  "Fast Hands",
  "Fearless",
  "Feed the Meat",
  "Filled to the Brim",
  "Fire Fiend",
  "Fitness",
  "Flame Flare",
  "Fleet",
  "Flicker",
  "Focus",
  "Forbearance",
  "Foresight",
  "Fuel the Blood",
  "Fuel the Fire",
  "Fuel the Rampage",
  "Girl Power",
  "Grenadier",
  "Grit",
  "Guided Missile",
  "Gun Crazy",
  "Hard To Get",
  "Hard to Kill",
  "Hardened",
  "Headsh0t",
  "Healthy",
  "Heavy Handed",
  "Helios",
  "High Velocity",
  "Hit & Run",
  "I'm the Juggernaut",
  "I'm Your Huckleberry",
  "Immolate",
  "Impact",
  "Incite",
  "Inner Glow",
  "Interspersed Outburst",
  "Intuition",
  "Ir0n Hand",
  "Iron Fist",
  "Juggernaut",
  "Just Got Real",
  "Kill C0nfirmed",
  "Killer",
  "Killing Bl0w",
  "Kinetic Reflection",
  "Last Ditch Effort",
  "Last Longer",
  "Lay Waste",
  "Lethal Strike",
  "Life Tap",
  "Like The Wind",
  "Liquidate",
  "Loaded",
  "Locked and Loaded",
  "Made of Sterner Stuff",
  "Master Blaster",
  "Metal Storm",
  "Mind Games",
  "Mind's Eye",
  "Money Shot",
  "More Pep",
  "Myelin",
  "Onslaught",
  "Out For Blood",
  "Out of Bubblegum",
  "Overload",
  "Pain is Power",
  "Pay Back",
  "Phase Strike",
  "Phoenix",
  "Potent as a Pony",
  "Precisi0n",
  "Predator",
  "Preparation",
  "Preshrunk Cyberpunk",
  "Pressure",
  "Prize Fighter",
  "Quick Charge",
  "Quick Draw",
  "Quicksilver",
  "Radiance",
  "Ranger",
  "Ransack",
  "Rapid Reload",
  "Ready",
  "Reaper",
  "Recompense",
  "Refire",
  "Relentless",
  "Resilience",
  "Resourceful",
  "Restoration",
  "Resurgence",
  "Revenge",
  "Revive",
  "Riotous Remedy",
  "Rising Sh0t",
  "Safeguard",
  "Salt the Wound",
  "Scattershot",
  "Sentry",
  "Sexual Tyrannosaurus",
  "Shock Storm",
  "Short Fuse",
  "Silence the Voices",
  "Silent Resolve",
  "Slayer",
  "Smaller, Lighter, Faster",
  "Spark",
  "Stat",
  "Steady",
  "Sting Like a Bee",
  "Stockpile",
  "Strength of Five Gorillas",
  "Striking",
  "Strip the Flesh",
  "Supply Drop",
  "Suspension",
  "Sustenance",
  "Sweet Release",
  "Swift Strike",
  "Swipe",
  "Taste of Blood",
  "The Better Half",
  "Thrill of the Kill",
  "Trespass",
  "Tw0Fang",
  "Typecast Iconoclast",
  "Unbreakable",
  "Unf0rseen",
  "Unstoppable Force",
  "Vel0city",
  "Venom",
  "Ward",
  "Wide Load",
  "Wires Don't Talk",
  "Wreck",
  "Yippee Ki Yay",
]);
