/**
 * Contains a curated list of item slugs highlighted in the Borderlands 2 showcase.
 *
 * @remarks
 * This array is used to feature selected items within the Borderlands 2 game in prominent application sections,
 * such as homepage showcases or featured carousels.
 */
export const SHOWCASE: string[] = [
  "amigo-sincero",
  "baby-maker",
  "badaboom",
  "bekah",
  "bitch",
  "blockhead",
  "bunny",
  "conference-call",
  "creamer",
  "deliverance",
  "grog-nozzle",
  "gub",
  "hail",
  "heart-breaker",
  "hellfire",
  "hive",
  "hornet",
  "hydra",
  "interfacer",
  "lady-fist",
  "longbow",
  "lyudmila",
  "norfleet",
  "ogre",
  "orphan-maker",
  "peak-opener",
  "pimpernel",
  "pitchfork",
  "sand-hawk",
  "sloth",
  "stinger",
  "tattler",
  "toothpick",
  "unkempt-harold",
  "volcano",
  "world-burn",
];